name: bet CI

on:
  push:
    branches: 
        - '**'
  pull_request:
    branches: 
        - '**'
jobs:

  linux-build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: 'master'
    - run: git fetch --prune --unshallow
    
    - name: apt update
      run: sudo apt-get update
      
    - name: Installing dependencies
      run: |
        sudo apt-get install software-properties-common autoconf git \
        build-essential libtool libprotobuf-c-dev libgmp-dev libsqlite3-dev \
        python python3 python3-mako zip libevent-dev pkg-config \
        libssl-dev libcurl4-gnutls-dev make libboost-all-dev automake \
        jq wget ninja-build libsqlite3-dev libgmp3-dev valgrind libcli-dev \
        libsecp256k1-dev libsodium-dev libbase58-dev nano
      
    - name: Installing Ninja
      run: sudo apt install ninja-build
      
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo $(git describe --always))"
      id: extract_branch

    # - name: Show Git Describe
    #   run: echo ${{ steps.extract_branch.outputs.branch }}

    - name: List files
      run: |
        pwd && \
        tar -czvf bet-linux-$(printf '%s' ${{ steps.extract_branch.outputs.branch }}).tar.gz privatebet/bet privatebet/config && \
        ls -lh bet-linux-$(printf '%s' ${{ steps.extract_branch.outputs.branch }}).tar.gz

    - name: Upload bet-linux release files
      uses: actions/upload-artifact@v2
      with:
        name: bet-linux-$(printf '%s' ${{ steps.extract_branch.outputs.branch }}).tar.gz
        path: /home/runner/work/bet/bet/bet-linux-$(printf '%s' ${{ steps.extract_branch.outputs.branch }}).tar.gz
